name: Generate Snake Game

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

#  # run on every push on the master branch
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v2
        id: snake-game-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark
            assets/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: './assets'
          branch: 'output'
          message: 'Generate Contribution Snake'     
#           push: "origin yourBranchName --set-upstream --force"

